### ISSUE TITLE
Lilypad missing texture

### ISSUE THREAD

**Issue by harrobe123** [FabianMPunkt/Nautilus3D#17] opened 2024-06-09 10:43 UTC
### Game Version

Labymod 4.2.17+1260 snapshot/fa7c7b44
Minecraft 1.20.6 (Modded)

### List all installed mods

architectury-12.1.3-fabric.jar
badpackets-fabric-0.7.3.jar
cloth-config-14.0.126-fabric.jar
Clumps-fabric-1.20.6-17.0.0.1.jar
continuity-3.0.0-beta.5+1.20.5.jar
entity_model_feature_fabric_1.20.5-2.0.2.jar
entity_texture_features_fabric_1.20.5-6.0.1.jar
fabric-api-0.99.4+1.20.6.jar
fastquit-3.0.0+1.20.6.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0+mc1.20.6.jar
modmenu-10.0.0-beta.1.jar
physics-mod-3.0.14-mc-1.20.6-fabric.jar
RoughlyEnoughItems-15.0.728-fabric.jar
sodium-fabric-0.5.8+mc1.20.6.jar
ViaFabricPlus-3.3.0.jar
wthit-fabric-11.2.0.jar

### List of all loaded packs

3DItemModels_1.19.4-1.20+_v1.7.0.zip
Banner Pattern Clarity v1.4 pf8-33.zip
Better_Dogs_V0.41.zip
betterbricks-e2370.zip
betterfroglights.zip
better-netherite-helmet-e1870.zip
clean-clock.zip
Clear Glass Pack 1.20.4.zip
Crops-3D_MC1.19_v1.2.0 (2).zip
CrosslessLamps-16x-1.19.3.zip
FreshAnimations_v1.9.zip
HD Paintings.zip
MandalasGUI+Dakmode_1.20.5.zip
Nautilus3D-V2.0.1.zip
Mattpack 1.20.zip
Shiny Trims v6 (Optifine).zip
skinmc-*username*-totem-pack.zip
Visible Ores2.12.zip
xali's Enchanted Books v0.12.0.zip

### Describe your issue

lilly pad missing texture showing purple black block thing

**Comment by harrobe123** [comment] 2024-06-15 09:34
> Hey can you post a screenshot of the broken lily pads with the F3 menu open? thanks!
![F3 Menu Open](https://github.com/FabianMPunkt/Nautilus3D/assets/74988522/38ad2d5b-4ba4-48d7-8b75-137e0882c52b)
![F3 Menu Closed](https://github.com/FabianMPunkt/Nautilus3D/assets/74988522/97f15c82-d722-412b-9f3e-3c10e102fa7a)

**Comment by harrobe123** [comment] 2024-06-15 09:37
this is with all mods and 1 shader pack but the only resource pack is nautilius  (it might be a tiny bit incompatible with complimentary reimagned as the portal is darker with the resource pack on very little impact though)

**Comment by FabianMPunkt** [comment] 2024-06-15 12:35
Thanks, i figured it out now:
The issue was initally caused by uppercase letters in the file names (#15) I thought that it was fixed but apparently both WinMerge and GitHub are not case sensitive by default. The fix will be in the next update. In the mean time you can manually update the files from this folder: https://github.com/FabianMPunkt/Nautilus3D/tree/main/Pack/Nautilus3D%20-%20%5B1.13%20%2B%5D/assets/minecraft/models/block/lily_pads

(0d0e84bdac58852cee006037121ef9c4db5f9c15)

**Closed by FabianMPunkt** 2024-06-15 12:35 UTC
Labels: bug
