### ISSUE TITLE
Far away terrain is glitchy/weird when playing with this pack

### ISSUE THREAD

**Issue by AagneyS** [FabianMPunkt/Nautilus3D#10] opened 2023-12-22 03:13 UTC
### Game Version

fabric loader 0.15.2 , Game Version 1.20.4

### List all installed mods

![w](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/0fbdf28e-bd42-437b-bc74-ce6d0ed108bd)
too many mods so i will upload a screenshot

### List of all loaded packs

Nautilus 3D-V1.9.1 , Sodium translations, chat reporting helper, fast better grass, mod menu helper, VanillaTweaks_r605454

### Describe your issue

far away terrain is glitchy/weird 
![2023-12-22_08 36 04](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/40b90c38-1fcb-40e6-af94-970b14c42508)

**Comment by FabianMPunkt** [comment] 2023-12-22 10:52
What exactly do you mean by "glitchy & weird"?
That fuzzynes you see is because of the fancy leaves, in combination with minecrafts complete lack of Anti-Aliasing.
For that reason we always recommend using some kind of shader, even if it is a super simple one.
If you are on lower-end hardware, i recommend the [Sildur's basic shader](https://sildurs-shaders.github.io/downloads/).

**Comment by AagneyS** [comment] 2023-12-23 07:12
> What exactly do you mean by "glitchy & weird"? That fuzzynes you see is because of the fancy leaves, in combination with minecrafts complete lack of Anti-Aliasing. For that reason we always recommend using some kind of shader, even if it is a super simple one. If you are on lower-end hardware, i recommend the [Sildur's basic shader](https://sildurs-shaders.github.io/downloads/).


I tried on fast graphics but its still the same.

**Comment by FabianMPunkt** [comment] 2023-12-23 12:42
Hmm if you are on really low-end hardware, you can try Sildur's Enhanced default (from the same link as before), or [Builders QOL Shader](https://modrinth.com/shader/builders-qol-shaders).
Please tell me if that works for you.

**Comment by AagneyS** [comment] 2023-12-24 04:47
> Hmm if you are on really low-end hardware, you can try Sildur's Enhanced default (from the same link as before), or [Builders QOL Shader](https://modrinth.com/shader/builders-qol-shaders). Please tell me if that works for you.

Hi there, I can't play Minecraft right now, but I have tried  both of those Shaders and I don't think my laptop can go any higher than 30 FPS. Is there any other ways to fix this issue without shaders?

**Comment by FabianMPunkt** [comment] 2023-12-24 15:27
You could try increasing the Mipmap levels (under Video Settings > Quality)
If that doesn't help, i suggest to remove the leaves completey:

- in file exporer goto Nautilus3D/assets/minecraft/blockstates
- search for "leaves" and delete every result

I know this is unfortunate but the problem is that vanilla minecraft completely lacks any sort of Anti-Aliasing. The only way around that is by using a shader.

**Comment by AagneyS** [comment] 2023-12-26 06:47
> You could try increasing the Mipmap levels (under Video Settings > Quality) If that doesn't help, i suggest to remove the leaves completey:
> 
> * in file exporer goto Nautilus3D/assets/minecraft/blockstates
> * search for "leaves" and delete every result
> 
> I know this is unfortunate but the problem is that vanilla minecraft completely lacks any sort of Anti-Aliasing. The only way around that is by using a shader.

Mipmap levels is set to 4, which is the max i can go.
I deleted leaves but its still the same, I don't think leaves are causing this because this fuzzyness is on other blocks too.
![Uploading 2023-12-26_12.14.43.png…]()

![Uploading 2023-12-26_12.14.43.png…]()

**Comment by AagneyS** [comment] 2023-12-26 06:48
![2023-12-26_12 14 43](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/dabbac34-4deb-425b-a8f0-68236e47efa8)

**Comment by AagneyS** [comment] 2023-12-26 10:00
i deleted all the mushroom textures from this pack (blockstates, models, custom_textures) and now its working fine LOL
![2023-12-26_15 27 33](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/f5bf562a-9a67-4d10-889d-c01c056600b3)

**Comment by FabianMPunkt** [comment] 2023-12-26 10:02
Hey, i just checked myself and it seems like the Mipmap levels somehow don't work at all with Nautilus3D enabled.
Good chatch with the mushroom textures.. i'm gonna have to take a deeper look at this now xD

**Comment by AagneyS** [comment] 2023-12-26 10:05
xD

**Comment by FabianMPunkt** [comment] 2023-12-26 10:36
Alright so i figured out what was causing the problems:
Some mushroom textures had a resolution of 16x17, or 16x19, istead of 16x16. This way the game could not correctly generate mipmap textures.
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/78741736/1d9c572f-ab25-4da2-9bad-3a5f89680047)
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/78741736/3d1699fe-7444-440d-8b3a-06aefa9d235f)

I remember Photoshop causing problems just like that.. Good thing i am using Krita now :D

The fix will be in the next Nautilus3D Update. For a temporary fix you can use the pack with all mushroom-related thigs removed, or you can maually replace the textures.
(01fb7d74c46f90977d2e4f35f3d5ef94cc4b91f0)

**Comment by AagneyS** [comment] 2023-12-26 10:46
Thanks :D

**Closed** 2023-12-26 10:53 UTC
Labels: bug
